spring:
#指定数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#指定Jpa属性
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  #指定跳转页面的前缀和后缀
  mvc:
    view:
      prefix: /
      suffix: .html
  #指定redis地址和端口
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 5
      max-wait: 1
      max-idle: 8
      min-idel: 0
server:
  port: 8081
